import { existsSync, realpathSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';

/**
 * What a production entry needs to start OpenTelemetry, decided at build time.
 *
 * Carried on the build context so the generator prints values rather than
 * working them out: which service this is, which product it belongs to, and
 * whether the packages to export with were there to build against.
 */
export interface TelemetryContext {
	/** `service.name` — the surface the server serves, or the app's directory. */
	serviceName: string;
	/** `service.namespace` — the workspace the app is part of. */
	serviceNamespace?: string;
	/**
	 * Whether `@geekmidas/telescope/instrumentation` and the OpenTelemetry
	 * packages it imports resolve from the app.
	 *
	 * They are optional peers, so an app may not have them. An entry built
	 * without them never imports them: the bundler would otherwise fail on the
	 * first one it cannot find, and an app that never asked for telemetry
	 * would stop building.
	 */
	available: boolean;
}

/**
 * Every package `@geekmidas/telescope/instrumentation` loads at runtime.
 *
 * All of them, rather than one as a proxy: the production bundle follows each
 * import, and a single missing one fails the build rather than the telemetry.
 */
export const TELEMETRY_PACKAGES = [
	'@opentelemetry/api',
	'@opentelemetry/auto-instrumentations-node',
	'@opentelemetry/exporter-logs-otlp-http',
	'@opentelemetry/exporter-trace-otlp-http',
	'@opentelemetry/instrumentation-pino',
	'@opentelemetry/resources',
	'@opentelemetry/sdk-logs',
	'@opentelemetry/sdk-node',
	'@opentelemetry/sdk-trace-base',
	'@opentelemetry/sdk-trace-node',
	'@opentelemetry/semantic-conventions',
] as const;

/**
 * The directory of `name` as `node_modules` lookup finds it from `fromDir`,
 * symlinks resolved — or undefined.
 *
 * The directory walk alone, not `require.resolve`: that also searches
 * `NODE_PATH`, which a package manager's bin shim sets to its own store, so a
 * `gkm build` run through one would find packages the app never installed —
 * and the bundler, which does not look there, would then fail on them.
 */
function packageDir(fromDir: string, name: string): string | undefined {
	for (let dir = resolve(fromDir); ; dir = dirname(dir)) {
		const candidate = join(dir, 'node_modules', name);
		if (existsSync(join(candidate, 'package.json'))) {
			return realpathSync(candidate);
		}
		if (dirname(dir) === dir) return undefined;
	}
}

/**
 * Whether the telemetry packages resolve the way the bundler will resolve them:
 * telescope from the app, and the OpenTelemetry packages from telescope —
 * where a peer is linked under pnpm, which need not be where the app sees it.
 */
export function telemetryResolvesFrom(appRoot: string): boolean {
	const telescope = packageDir(appRoot, '@geekmidas/telescope');
	if (!telescope) return false;

	return TELEMETRY_PACKAGES.every((pkg) => packageDir(telescope, pkg));
}

/** The telemetry half of a build context. */
export function telemetryFor(options: {
	appRoot: string;
	surfaceId?: string;
	workspaceName?: string;
}): TelemetryContext {
	return {
		serviceName: options.surfaceId ?? basename(options.appRoot),
		...(options.workspaceName && { serviceNamespace: options.workspaceName }),
		available: telemetryResolvesFrom(options.appRoot),
	};
}

const HEADER = `/**
 * Generated by 'gkm build --production'.
 *
 * Starts OpenTelemetry when OTEL_EXPORTER_OTLP_ENDPOINT names a collector, and
 * does nothing otherwise: without it, the telemetry packages are not loaded.
 * The standard OTEL_* variables (OTEL_TRACES_SAMPLER, OTEL_TRACES_SAMPLER_ARG,
 * OTEL_EXPORTER_OTLP_HEADERS, OTEL_RESOURCE_ATTRIBUTES, OTEL_SERVICE_NAME)
 * configure the rest.
 */

import type { MiddlewareHandler } from 'hono';

export interface StartTelemetryOptions {
  /** Requests whose spans would only be noise: health checks, by default. */
  ignorePaths?: string[];
  /**
   * The API's own sites — the origins its CORS allows — read on each request.
   * Their \`traceparent\` is continued, as is an internal caller's; anyone
   * else's starts a new trace linked to the one it claimed.
   */
  trustedOrigins?: () => readonly string[];
}

/** Telemetry was asked for and cannot start. The server runs without it. */
export class TelemetryUnavailable extends Error {
  constructor(readonly reason: string, options?: { cause?: unknown }) {
    super(
      \`OTEL_EXPORTER_OTLP_ENDPOINT is set, but \${reason} This server exports no traces or logs until that is fixed.\`,
      options,
    );
    this.name = 'TelemetryUnavailable';
  }
}
`;

/**
 * The entry's `telemetry.ts`: a `startTelemetry()` the server awaits before it
 * imports the app, so the libraries the app loads are instrumented. It returns
 * the Hono middleware that traces each request, or undefined when telemetry is
 * off — the server mounts it ahead of every route.
 *
 * Failing to start telemetry warns (a named `TelemetryUnavailable`, through
 * `process.emitWarning`) and never stops the server: an outage in observability
 * is not a reason to have an outage in the service.
 */
export function generateTelemetryModule(
	telemetry: TelemetryContext | undefined,
): string {
	if (!telemetry?.available) {
		return `${HEADER}
export async function startTelemetry(
  _options: StartTelemetryOptions = {},
): Promise<MiddlewareHandler | undefined> {
  if (!process.env.OTEL_EXPORTER_OTLP_ENDPOINT) return undefined;

  process.emitWarning(
    new TelemetryUnavailable(
      'this server was built without @geekmidas/telescope and the @opentelemetry packages it needs. Add them to the app and rebuild.',
    ),
  );
  return undefined;
}
`;
	}

	const options = [
		`serviceName: ${JSON.stringify(telemetry.serviceName)},`,
		...(telemetry.serviceNamespace
			? [`serviceNamespace: ${JSON.stringify(telemetry.serviceNamespace)},`]
			: []),
		// The stage the deploy set, so one service's stages stay apart.
		'deploymentEnvironment: process.env.STAGE,',
		// The exporters read OTEL_EXPORTER_OTLP_* themselves, and the SDK reads
		// OTEL_TRACES_SAMPLER — so no endpoint and no ratio are printed here.
		// The server's own shutdown decides when the process exits.
		'handleSignals: false,',
		// Neither is left to module-load hooks, which see nothing inside a
		// bundle: @geekmidas/logger emits each record through the logs API
		// itself, and the middleware returned below opens each request's span.
		// Hooked as well where they can be, every record and request would be
		// sent twice.
		'instrumentPino: false,',
		'incomingHttpSpans: false,',
	];

	return `${HEADER}
export async function startTelemetry(
  options: StartTelemetryOptions = {},
): Promise<MiddlewareHandler | undefined> {
  if (!process.env.OTEL_EXPORTER_OTLP_ENDPOINT) return undefined;

  let instrumentation;
  try {
    instrumentation = await import('@geekmidas/telescope/instrumentation');
  } catch (cause) {
    process.emitWarning(
      new TelemetryUnavailable(
        '@geekmidas/telescope/instrumentation or an @opentelemetry package it needs could not be loaded. Install them in the app and rebuild.',
        { cause },
      ),
    );
    return undefined;
  }

  instrumentation.setupTelemetry({
    ${options.join('\n    ')}
  });

  // Flush what is buffered when the process is told to stop. When nothing
  // else handles the signal, re-raise it once flushed, so the process still
  // stops the way it would have without this listener.
  for (const signal of ['SIGTERM', 'SIGINT'] as const) {
    process.once(signal, () => {
      void instrumentation.flushTelemetry().finally(() => {
        if (process.listenerCount(signal) === 0) process.kill(process.pid, signal);
      });
    });
  }

  // A SERVER span per request, opened by the app itself rather than by
  // hooking node:http: \`GET /users/:id\`, continuing an incoming traceparent
  // from the API's own sites and internal callers (a new, linked trace from
  // anyone else), with the handler — its logs, fetches and queries — running
  // inside it.
  return instrumentation.honoTelemetryMiddleware({
    ignorePaths: options.ignorePaths,
    trustedOrigins: options.trustedOrigins,
  });
}
`;
}
