/**
 * The stack's own edge, rendered for Caddy: one site block per route.
 *
 * Deployed, each host is the stage's real domain and Caddy gets it a
 * certificate from Let's Encrypt on first request — the same automatic HTTPS
 * it does anywhere, with nothing to configure but the name — or serves the
 * stage's own certificate (`deploy.compose.tls`). Locally the hosts are
 * `*.localhost` and the certificates come from Caddy's own CA, as the `gkm
 * dev` edge does, so a local stack is `https://` like a deployed one.
 *
 * Pure: the routes are data (`routes.ts`), and rendering them is one string.
 */

import { CLIENT_IP_HEADER } from '@geekmidas/manifest';
import type { EdgeRoute, EdgeTls, Upstream } from './routes.js';

/** Where Caddy reads a stage's own certificate, inside its container. */
export const CADDY_TLS_DIR = '/etc/caddy/tls';

export interface CaddyfileOptions {
	tls: EdgeTls;
	/** Where ACME sends expiry notices, when someone wants them. */
	email?: string;
}

/** An upstream on the stack's own network: its service name. */
function address({ service, port }: Upstream): string {
	return `${service}:${port}`;
}

/** The Caddyfile for a stack's edge. */
export function edgeCaddyfile(
	routes: readonly EdgeRoute[],
	options: CaddyfileOptions,
): string {
	const { tls } = options;
	const global =
		tls.kind === 'internal'
			? `{
	# No ACME and no public DNS: the CA is Caddy's own and the names resolve
	# to this machine.
	local_certs
	auto_https disable_redirects
}`
			: options.email
				? `{
	email ${options.email}
}`
				: '';

	const certificate =
		tls.kind === 'internal'
			? `
	tls internal
`
			: tls.kind === 'files'
				? `
	tls ${tls.certFile} ${tls.keyFile}
`
				: '';

	const blocks = routes.map(
		({
			host,
			upstreams,
			prefix,
			allow,
			streaming,
		}) => `https://${host} {${certificate}
	# gkm's own header, which only a service of this stack may send: the auth
	# server rate-limits by the client address it carries.
	request_header -${CLIENT_IP_HEADER}
${
	allow
		? `
	# Only these addresses — the peer Caddy sees, never a header a client
	# could set. Everything else is refused before it reaches the upstream.
	@denied not remote_ip ${allow.join(' ')}
	respond @denied 403
`
		: ''
}${
	prefix
		? `
	# A bucket, served at a host of its own: the bucket is a prefix on MinIO,
	# which routes and signs on the Host header — so it is sent the upstream's.
	reverse_proxy ${upstreams.map(address).join(' ')} {
		rewrite ${prefix}{uri}
		header_up Host {upstream_hostport}
	}`
		: `
	# Host and X-Forwarded-* are passed through as Caddy does by default, so
	# an app builds redirects, cookies and links on the address a caller used.
	reverse_proxy ${upstreams.map(address).join(' ')}${
		streaming
			? ` {
		# Never buffer: a streamed response — server-sent events, a Next.js
		# RSC payload — reaches the client as each chunk is written.
		flush_interval -1
	}`
			: ''
	}`
}
}`,
	);

	// No blank line under the header: `caddy fmt` wants the first block there.
	return `${HEADER}${global ? `${global}\n\n` : ''}${blocks.join('\n\n')}\n`;
}

const HEADER = `# Generated by gkm compose from the construct manifest — do not edit.
#
# One host per API and site, each in front of its own container, one per
# file server in front of the stack's MinIO, and — when its logs are served
# publicly — one for OpenObserve, to the addresses it allows.
`;
