/**
 * The edge in front of a compose stack: one Caddy, one host per app.
 *
 * Deployed, each host is the stage's real domain and Caddy gets it a
 * certificate from Let's Encrypt on first request — the same automatic HTTPS
 * it does anywhere, with nothing to configure but the name. Locally the hosts
 * are `*.localhost` and the certificates come from Caddy's own CA, as the
 * `gkm dev` edge does, so a local stack is `https://` like a deployed one.
 *
 * Pure: what the edge serves is data, and rendering it is one string.
 */

/** One host on the edge and the app container behind it. */
export interface EdgeSite {
	/** e.g. `api.example.com` */
	host: string;
	/** The app on the compose network, e.g. `api:3000`. */
	upstream: string;
}

export interface EdgeOptions {
	/** Certificates from Caddy's internal CA rather than from ACME. */
	local: boolean;
	/** Where ACME sends expiry notices, when someone wants them. */
	email?: string;
}

/** The Caddyfile for a stack's edge. */
export function edgeCaddyfile(
	sites: readonly EdgeSite[],
	options: EdgeOptions,
): string {
	const global = options.local
		? `{
	# No ACME and no public DNS: the CA is Caddy's own and the names resolve
	# to this machine.
	local_certs
	auto_https disable_redirects
}`
		: options.email
			? `{
	email ${options.email}
}`
			: '';

	const blocks = sites.map(
		({ host, upstream }) => `https://${host} {${
			options.local
				? `
	tls internal
`
				: ''
		}
	# Host and X-Forwarded-* are passed through as Caddy does by default, so
	# an app builds redirects, cookies and links on the address a caller used.
	reverse_proxy ${upstream} {
		# Never buffer: a streamed response — server-sent events, a Next.js
		# RSC payload — reaches the client as each chunk is written.
		flush_interval -1
	}
}`,
	);

	// No blank line under the header: `caddy fmt` wants the first block there.
	return `${HEADER}${global ? `${global}\n\n` : ''}${blocks.join('\n\n')}\n`;
}

const HEADER = `# Generated by gkm compose from the construct manifest — do not edit.
#
# One host per API and site, each in front of its own container.
`;
