/**
 * The edge in front of a compose stack: one Caddy, one host per app.
 *
 * Deployed, each host is the stage's real domain and Caddy gets it a
 * certificate from Let's Encrypt on first request — the same automatic HTTPS
 * it does anywhere, with nothing to configure but the name. Locally the hosts
 * are `*.localhost` and the certificates come from Caddy's own CA, as the
 * `gkm dev` edge does, so a local stack is `https://` like a deployed one.
 *
 * Pure: what the edge serves is data, and rendering it is one string.
 */

/** One host on the edge and the app container behind it. */
export interface EdgeSite {
	/** e.g. `api.example.com` */
	host: string;
	/** The app on the compose network, e.g. `api:3000`. */
	upstream: string;
	/**
	 * A path to rewrite to, where the upstream expects a different one: a
	 * file server's bucket, as a prefix on MinIO — `/uploads{uri}`.
	 */
	rewrite?: string;
	/**
	 * The client addresses (IPs or CIDRs) it answers; every other is
	 * refused with 403. Absent, it answers everyone.
	 */
	allow?: readonly string[];
}

export interface EdgeOptions {
	/** Certificates from Caddy's internal CA rather than from ACME. */
	local: boolean;
	/** Where ACME sends expiry notices, when someone wants them. */
	email?: string;
}

/** The Caddyfile for a stack's edge. */
export function edgeCaddyfile(
	sites: readonly EdgeSite[],
	options: EdgeOptions,
): string {
	const global = options.local
		? `{
	# No ACME and no public DNS: the CA is Caddy's own and the names resolve
	# to this machine.
	local_certs
	auto_https disable_redirects
}`
		: options.email
			? `{
	email ${options.email}
}`
			: '';

	const blocks = sites.map(
		({ host, upstream, rewrite, allow }) => `https://${host} {${
			options.local
				? `
	tls internal
`
				: ''
		}${
			allow
				? `
	# Only these addresses — the peer Caddy sees, never a header a client
	# could set. Everything else is refused before it reaches the upstream.
	@denied not remote_ip ${allow.join(' ')}
	respond @denied 403
`
				: ''
		}${
			rewrite
				? `
	# A bucket, served at a host of its own: the bucket is a prefix on MinIO,
	# which routes and signs on the Host header — so it is sent the upstream's.
	reverse_proxy ${upstream} {
		rewrite ${rewrite}
		header_up Host {upstream_hostport}
	}`
				: `
	# Host and X-Forwarded-* are passed through as Caddy does by default, so
	# an app builds redirects, cookies and links on the address a caller used.
	reverse_proxy ${upstream} {
		# Never buffer: a streamed response — server-sent events, a Next.js
		# RSC payload — reaches the client as each chunk is written.
		flush_interval -1
	}`
		}
}`,
	);

	// No blank line under the header: `caddy fmt` wants the first block there.
	return `${HEADER}${global ? `${global}\n\n` : ''}${blocks.join('\n\n')}\n`;
}

const HEADER = `# Generated by gkm compose from the construct manifest — do not edit.
#
# One host per API and site, each in front of its own container, one per
# file server in front of the stack's MinIO, and — when its logs are served
# publicly — one for OpenObserve, to the addresses it allows.
`;
