import type { StagesConfig } from '../../workspace/types.js';
import { apiTemplate } from './api.js';
import { minimalTemplate } from './minimal.js';
import { serverlessTemplate } from './serverless.js';
import { workerTemplate } from './worker.js';

/**
 * OpenAPI output path (fixed, not configurable)
 */

/**
 * Endpoints output path (generated by gkm dev/build)
 */

/**
 * Logger implementation type
 */
export type LoggerType = 'pino' | 'console';

/**
 * Routes structure pattern
 */
export type RoutesStructure =
	| 'centralized-endpoints'
	| 'centralized-routes'
	| 'domain-based';

/**
 * Package manager type
 */
export type PackageManager = 'pnpm' | 'npm' | 'yarn' | 'bun';

/**
 * Deploy target type
 */
export type DeployTarget = 'dokploy' | 'sst' | 'none';

/**
 * The constructs a scaffold declares.
 *
 * Constructs, not containers: `Database` is a `KyselyDatabase`, `Uploads` an
 * `ObjectStorage`. Which container runs each locally, and which backend serves
 * it deployed, follow from the declaration and the deploy target — nothing
 * here names a Postgres or a Redis.
 */
export interface ScaffoldedConstructs {
	database: boolean;
	cache: boolean;
	uploads: boolean;
	mail: boolean;
}

/**
 * Frontend framework for the fullstack template's client app.
 * Limited to the three with first-class scaffolds; the wider
 * `FrontendFramework` type also covers `vite` and `remix` which
 * users can configure manually after init.
 */
export type FullstackFrontendFramework = 'nextjs' | 'tanstack-start' | 'expo';

/**
 * Options collected from user prompts
 */
export interface TemplateOptions {
	name: string;
	template: TemplateName;
	telescope: boolean;
	studio: boolean;
	loggerType: LoggerType;
	routesStructure: RoutesStructure;
	monorepo: boolean;
	/** Path for the API app in monorepo (e.g., 'apps/api') */
	apiPath: string;
	/** Selected package manager */
	packageManager: PackageManager;
	/** Deploy target */
	deployTarget: DeployTarget;
	/** The AWS region, when `deployTarget` is `sst` */
	region?: string;
	/** The project's stages, written to gkm.config.ts and read from it */
	stages: StagesConfig;
	/** The constructs this scaffold declares */
	constructs: ScaffoldedConstructs;
	/** Frontend framework (fullstack template only) */
	frontendFramework?: FullstackFrontendFramework;
}

/**
 * A file to be generated
 */
export interface GeneratedFile {
	path: string;
	content: string;
}

/**
 * Template configuration
 */
export interface TemplateConfig {
	name: TemplateName;
	description: string;
	dependencies: Record<string, string>;
	devDependencies: Record<string, string>;
	scripts: Record<string, string>;
	files: (options: TemplateOptions) => GeneratedFile[];
}

export type TemplateName =
	| 'minimal'
	| 'api'
	| 'serverless'
	| 'worker'
	| 'fullstack';

/**
 * All available templates
 */
export const templates: Record<
	Exclude<TemplateName, 'fullstack'>,
	TemplateConfig
> = {
	minimal: minimalTemplate,
	api: apiTemplate,
	serverless: serverlessTemplate,
	worker: workerTemplate,
};

/**
 * Template choices for prompts (Story 1.11 simplified to api + fullstack)
 */
export const templateChoices = [
	{
		title: 'API',
		value: 'api' as TemplateName,
		description: 'Single backend API with endpoints',
	},
	{
		title: 'Fullstack',
		value: 'fullstack' as TemplateName,
		description: 'Monorepo with API + Next.js + shared models',
	},
];

/**
 * All template choices (includes advanced options)
 */
export const allTemplateChoices = [
	{
		title: 'Minimal',
		value: 'minimal' as TemplateName,
		description: 'Basic health endpoint',
	},
	{
		title: 'API',
		value: 'api' as TemplateName,
		description: 'Full API with auth, database, services',
	},
	{
		title: 'Fullstack',
		value: 'fullstack' as TemplateName,
		description: 'Monorepo with API + Next.js + shared models',
	},
	{
		title: 'Serverless',
		value: 'serverless' as TemplateName,
		description: 'AWS Lambda handlers',
	},
	{
		title: 'Worker',
		value: 'worker' as TemplateName,
		description: 'Background job processing',
	},
];

/**
 * Frontend framework choices for the fullstack template prompt.
 */
export const frontendFrameworkChoices = [
	{
		title: 'Next.js',
		value: 'nextjs' as FullstackFrontendFramework,
		description: 'React server components, app router (default)',
	},
	{
		title: 'TanStack Start',
		value: 'tanstack-start' as FullstackFrontendFramework,
		description: 'File-based router on Vite + Nitro',
	},
	{
		title: 'Expo',
		value: 'expo' as FullstackFrontendFramework,
		description: 'React Native mobile app (iOS + Android)',
	},
];

/**
 * Logger type choices for prompts
 */
export const loggerTypeChoices = [
	{
		title: 'Pino',
		value: 'pino' as LoggerType,
		description: 'Fast JSON logger for production (recommended)',
	},
	{
		title: 'Console',
		value: 'console' as LoggerType,
		description: 'Simple console logger for development',
	},
];

/**
 * Routes structure choices for prompts
 */
export const routesStructureChoices = [
	{
		title: 'Centralized (endpoints)',
		value: 'centralized-endpoints' as RoutesStructure,
		description: 'src/endpoints/**/*.ts',
	},
	{
		title: 'Centralized (routes)',
		value: 'centralized-routes' as RoutesStructure,
		description: 'src/routes/**/*.ts',
	},
	{
		title: 'Domain-based',
		value: 'domain-based' as RoutesStructure,
		description: 'src/**/routes/*.ts (e.g., src/users/routes/list.ts)',
	},
];

/**
 * Package manager choices for prompts
 */
export const packageManagerChoices = [
	{
		title: 'pnpm',
		value: 'pnpm' as PackageManager,
		description: 'Fast, disk space efficient (recommended)',
	},
	{
		title: 'npm',
		value: 'npm' as PackageManager,
		description: 'Node.js default package manager',
	},
	{
		title: 'yarn',
		value: 'yarn' as PackageManager,
		description: 'Yarn package manager',
	},
	{
		title: 'bun',
		value: 'bun' as PackageManager,
		description: 'Fast JavaScript runtime and package manager',
	},
];

/**
 * Deploy target choices for prompts
 */
export const deployTargetChoices = [
	{
		title: 'Dokploy',
		value: 'dokploy' as DeployTarget,
		description: 'Deploy to Dokploy (Docker-based hosting)',
	},
	{
		title: 'AWS (SST)',
		value: 'sst' as DeployTarget,
		description: 'Deploy to your AWS account through SST',
	},
	{
		title: 'Configure later',
		value: 'none' as DeployTarget,
		description: 'Skip deployment setup for now',
	},
];

/**
 * Which constructs to declare.
 *
 * The containers that run them locally and the backends that serve them
 * deployed are derived from these, so the prompt names only what the code
 * will say.
 */
export const constructChoices: {
	title: string;
	value: keyof ScaffoldedConstructs;
	description: string;
}[] = [
	{
		title: 'Database',
		value: 'database',
		description: 'KyselyDatabase — Postgres',
	},
	{
		title: 'Cache',
		value: 'cache',
		description: 'Cache — backed by what the deploy target implies',
	},
	{
		title: 'Uploads',
		value: 'uploads',
		description: 'ObjectStorage — a bucket',
	},
	{
		title: 'Mail',
		value: 'mail',
		description: 'Email — outbound mail over SMTP',
	},
];

/**
 * Get a template by name
 */
export function getTemplate(name: TemplateName): TemplateConfig | null {
	if (name === 'fullstack') {
		// Fullstack template is handled specially, uses api template as base
		return templates.api;
	}
	const template = templates[name];
	if (!template) {
		throw new Error(`Unknown template: ${name}`);
	}
	return template;
}

/**
 * Check if a template is the fullstack monorepo template
 */
export function isFullstackTemplate(name: TemplateName): boolean {
	return name === 'fullstack';
}
