/**
 * `.gkm/stages.d.ts`: the declared stages, as types application code can see.
 *
 * Constructs and app code cannot import `gkm.config.ts`, so the stage names it
 * declares were plain strings everywhere else. This writes them into
 * `@geekmidas/constructs`' `Stages` interface, which `LocalStage`,
 * `DeployedStage` and `AnyStage` read — an `ExternalApi` url keyed `prodution`
 * becomes a type error. Without the file those types are `string`.
 *
 * Written by `gkm dev`, `gkm build` and `gkm test --prepare`, beside the
 * generated clients; a project's tsconfig `include`s it.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { StagesConfig } from './types.js';

/** Where the declaration is written, relative to the workspace root. */
export const STAGE_TYPES_FILE = '.gkm/stages.d.ts';

/** A union of string literal types: `'staging' | 'prod'`, or `never`. */
function union(names: readonly string[]): string {
	// Stage names are validated lowercase letters, digits and hyphens, so a
	// single-quoted literal needs no escaping.
	return names.length ? names.map((name) => `'${name}'`).join(' | ') : 'never';
}

/** The declaration for a stages block. */
export function stageTypesDeclaration(stages: StagesConfig): string {
	return `// Generated by gkm from the \`stages\` in gkm.config.ts — do not edit.
// \`gkm dev\`, \`gkm build\` and \`gkm test --prepare\` rewrite it.
export {};

declare module '@geekmidas/constructs' {
	interface Stages {
		local: ${union([stages.local])};
		deployed: ${union(stages.deployed)};
	}
}
`;
}

/**
 * Write `.gkm/stages.d.ts` under the workspace root, and return its path — or
 * nothing when there are no stages to write. Left untouched when unchanged, so
 * an editor's watcher does not re-check the project on every start.
 */
export async function writeStageTypes(
	root: string,
	stages: StagesConfig | undefined,
): Promise<string | undefined> {
	if (!stages) return undefined;

	const path = join(root, STAGE_TYPES_FILE);
	const content = stageTypesDeclaration(stages);
	const existing = await readFile(path, 'utf8').catch(() => undefined);
	if (existing === content) return path;

	await mkdir(join(root, '.gkm'), { recursive: true });
	await writeFile(path, content);
	return path;
}
