#!/usr/bin/env tsx
/**
 * Script to embed the built UI assets into a TypeScript file.
 * This allows the telescope package to serve the UI without external files.
 */
import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const uiDistPath = join(__dirname, '../dist/ui');
const outputPath = join(__dirname, '../src/ui-assets.ts');

interface Asset {
  path: string;
  content: string;
  contentType: string;
}

function getContentType(filename: string): string {
  if (filename.endsWith('.html')) return 'text/html';
  if (filename.endsWith('.css')) return 'text/css';
  if (filename.endsWith('.js')) return 'application/javascript';
  if (filename.endsWith('.map')) return 'application/json';
  return 'application/octet-stream';
}

function collectAssets(dir: string, basePath: string = ''): Asset[] {
  const assets: Asset[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    const assetPath = basePath ? `${basePath}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      assets.push(...collectAssets(fullPath, assetPath));
    } else if (!entry.name.endsWith('.map')) {
      // Skip source maps
      const content = readFileSync(fullPath, 'utf-8');
      assets.push({
        path: assetPath,
        content,
        contentType: getContentType(entry.name),
      });
    }
  }

  return assets;
}

try {
  const assets = collectAssets(uiDistPath);

  // Find the index.html to extract references
  const indexHtml = assets.find((a) => a.path === 'index.html');
  if (!indexHtml) {
    console.error('index.html not found in build output');
    process.exit(1);
  }

  // Generate TypeScript file
  const output = `// Auto-generated file - do not edit directly
// Generated by scripts/embed-ui.ts

export interface UIAsset {
  path: string;
  content: string;
  contentType: string;
}

export const UI_ASSETS: UIAsset[] = ${JSON.stringify(assets, null, 2)};

export function getAsset(path: string): UIAsset | undefined {
  // Normalize path
  const normalized = path.replace(/^\\//, '');
  return UI_ASSETS.find((a) => a.path === normalized);
}

export function getIndexHtml(): string {
  const asset = UI_ASSETS.find((a) => a.path === 'index.html');
  return asset?.content ?? '';
}
`;

  writeFileSync(outputPath, output);
  console.log(`Embedded ${assets.length} UI assets into ${outputPath}`);
} catch (error) {
  console.error('Error embedding UI assets:', error);
  process.exit(1);
}
