#!/usr/bin/env tsx
/**
 * Script to embed built UI assets into a TypeScript file.
 * This allows packages to serve the UI without external files.
 *
 * Usage: embed-ui <input-dir> <output-file>
 * Example: embed-ui dist/ui src/ui-assets.ts
 */
import { readFileSync, readdirSync, writeFileSync } from 'fs';

interface Asset {
  path: string;
  content: string;
  contentType: string;
}

function getContentType(filename: string): string {
  if (filename.endsWith('.html')) return 'text/html';
  if (filename.endsWith('.css')) return 'text/css';
  if (filename.endsWith('.js')) return 'application/javascript';
  if (filename.endsWith('.map')) return 'application/json';
  return 'application/octet-stream';
}

function collectAssets(dir: string, basePath: string = ''): Asset[] {
  const assets: Asset[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = `${dir}/${entry.name}`;
    const assetPath = basePath ? `${basePath}/${entry.name}` : entry.name;

    if (entry.isDirectory()) {
      assets.push(...collectAssets(fullPath, assetPath));
    } else if (!entry.name.endsWith('.map')) {
      // Skip source maps
      const content = readFileSync(fullPath, 'utf-8');
      assets.push({
        path: assetPath,
        content,
        contentType: getContentType(entry.name),
      });
    }
  }

  return assets;
}

const args = process.argv.slice(2);
if (args.length !== 2) {
  console.error('Usage: embed-ui <input-dir> <output-file>');
  console.error('Example: embed-ui dist/ui src/ui-assets.ts');
  process.exit(1);
}

const [inputDir, outputFile] = args;

try {
  const assets = collectAssets(inputDir);

  // Find the index.html to extract references
  const indexHtml = assets.find((a) => a.path === 'index.html');
  if (!indexHtml) {
    console.error('index.html not found in build output');
    process.exit(1);
  }

  // Generate TypeScript file
  const output = `// Auto-generated file - do not edit directly
// Generated by @geekmidas/ui/scripts/embed-ui.ts

export interface UIAsset {
  path: string;
  content: string;
  contentType: string;
}

export const UI_ASSETS: UIAsset[] = ${JSON.stringify(assets, null, 2)};

export function getAsset(path: string): UIAsset | undefined {
  // Normalize path
  const normalized = path.replace(/^\\//, '');
  return UI_ASSETS.find((a) => a.path === normalized);
}

export function getIndexHtml(): string {
  const asset = UI_ASSETS.find((a) => a.path === 'index.html');
  return asset?.content ?? '';
}
`;

  writeFileSync(outputFile, output);
  console.error(`Embedded ${assets.length} UI assets into ${outputFile}`);
} catch (error) {
  console.error('Error embedding UI assets:', error);
  process.exit(1);
}
