/**
 * The stack's `backups` service: what a deployed compose stage with Postgres
 * runs beside its apps, unless `deploy.backups.<stage>` is `false`.
 *
 * - **The image** is built from the stack's own Postgres image —
 *   `postgres:<major>-alpine`, already on the server for the stack, and with
 *   the `pg_dump` that matches the server — with Node added and gkm's runner
 *   (`runner.ts`) copied in. Nothing is pulled that the stack does not have,
 *   and nothing is mounted from the host: the build context is two files.
 * - **Its key** is `BACKUPS_URL`, from the stage's secrets, like any app's:
 *   allowed to put objects under the stage's backups prefix and nothing else.
 *   The server holds no AWS credentials of its own.
 * - **Its login** is a role of its own, `<project>_backups`, granted
 *   `pg_read_all_data` — it can read every database and write none. Postgres
 *   before 14 has no such role, and there it signs in as the stack's
 *   superuser.
 * - **Its health** is the last good run: unhealthy once that is more than
 *   twice the schedule's longest gap old, after a startup grace.
 */

import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_POSTGRES_VERSION } from '@geekmidas/manifest';
import { GkmError } from '../errors';
import { postgresImage } from '../reconcile/containers.js';
import { localRolePassword } from '../reconcile/env.js';
import { postgresRoleSlug } from '../reconcile/localCredentials.js';
import type { Plan } from '../reconcile/plan.js';
import { quoteIdentifier, type Statement } from '../reconcile/provision.js';
import {
	type BackupDatabase,
	type BackupsWorkspace,
	backupDatabases,
	backupsPrefix,
} from './config.js';
import type { StageBackups } from './schedule.js';

/** The service's name in the stack. */
export const BACKUPS_SERVICE = 'backups';

/** The secret its key is written to. */
export const BACKUPS_URL_KEY = 'BACKUPS_URL';

/** Where the runner is, in the image. */
export const RUNNER_PATH = '/gkm/backup.mjs';

/** The first Postgres with `pg_read_all_data`. */
const READ_ALL_DATA_SINCE = 14;

/** A stage that backs up, and no key to back up with. */
export class BackupsUrlMissing extends GkmError {
	constructor(readonly stage: string) {
		super(
			`'${stage}' runs Postgres, so its stack backs it up, and its secrets ` +
				`hold no ${BACKUPS_URL_KEY} to back up with. The deploy writes it — ` +
				"the IAM user and key it creates in the stage's AWS account — so " +
				'run the deploy with the ' +
				"account's credentials. To take no backups on this stage, set " +
				`deploy.backups.${stage}: false.`,
		);
		this.name = 'BackupsUrlMissing';
	}
}

/** The backups role: `<project>_backups`, as the superuser is `<project>_admin`. */
export function backupsRole(project: string): string {
	return `${postgresRoleSlug(project)}_backups`;
}

/** The stack's backups, as its compose file and env file have them. */
export interface StackBackups {
	backups: StageBackups;
	databases: BackupDatabase[];
	/** `gkm/<project>/<stage>/backups`. */
	prefix: string;
	/** The Postgres image it is built from. */
	from: string;
	/** `<project>-backups:pg18-<hash>`: built on the server, never pushed. */
	image: string;
	/** Its build context: the Dockerfile and the runner. */
	files: { Dockerfile: string; 'backup.mjs': string };
	/** What it signs in to Postgres as. */
	login: { user: string; password: string };
	/** Whether that is its own read-only role (else the superuser). */
	readOnly: boolean;
	/** Its environment — empty in a stack that only builds. */
	env: Record<string, string>;
}

/**
 * The runner's source, as JavaScript: the built `backups/runner.mjs` beside
 * the CLI's bundle, or — run from source — `runner.ts`, with its types
 * stripped by esbuild.
 */
export function runnerSource(): string {
	const here = dirname(fileURLToPath(import.meta.url));
	for (const path of [
		join(here, 'backups', 'runner.mjs'),
		join(here, 'runner.mjs'),
		join(here, '..', 'backups', 'runner.mjs'),
	]) {
		if (existsSync(path)) return readFileSync(path, 'utf-8');
	}
	const { transformSync } = createRequire(import.meta.url)(
		'esbuild',
	) as typeof import('esbuild');
	return transformSync(readFileSync(join(here, 'runner.ts'), 'utf-8'), {
		loader: 'ts',
		format: 'esm',
		target: 'node22',
	}).code;
}

/** The image's Dockerfile: the stack's Postgres, Node, and the runner. */
export function backupsDockerfile(from: string): string {
	return `# Generated by gkm — the stage's backups: pg_dump from ${from}, and gkm's uploader.
FROM ${from}
RUN apk add --no-cache nodejs
COPY backup.mjs ${RUNNER_PATH}
USER postgres
ENTRYPOINT []
CMD ["node", "${RUNNER_PATH}", "serve"]
`;
}

export interface StackBackupsInput {
	workspace: BackupsWorkspace;
	stage: string;
	project: string;
	plan: Plan;
	backups: StageBackups;
	/** The stage's secrets, by key. */
	custom: Readonly<Record<string, string>>;
	seed: string;
	/** The stack's superuser. */
	superuser: { user: string; password: string };
	/** What the stage's telemetry hands a process, when it is on. */
	telemetry?: Readonly<Record<string, string>>;
	/** The stack only builds: no environment, no key needed. */
	buildOnly?: boolean;
}

/**
 * The stack's backups service, for a stage whose backups are on.
 *
 * @throws {BackupsUrlMissing} when the stage's secrets hold no key
 */
export function stackBackups(input: StackBackupsInput): StackBackups {
	const { plan, stage } = input;
	const version =
		plan.resources.find((r) => r.version)?.version ?? DEFAULT_POSTGRES_VERSION;
	const from = postgresImage(version);
	const script = runnerSource();
	const dockerfile = backupsDockerfile(from);
	const hash = createHash('sha256')
		.update(dockerfile)
		.update(script)
		.digest('hex')
		.slice(0, 12);

	const readOnly = version >= READ_ALL_DATA_SINCE;
	const role = backupsRole(input.workspace.name);
	const login = readOnly
		? {
				user: role,
				password: localRolePassword(
					input.workspace.name,
					plan,
					role,
					input.seed,
				),
			}
		: input.superuser;

	const databases = backupDatabases(plan.resources);
	const prefix = backupsPrefix(input.workspace, stage);
	const { kind, ...schedule } = input.backups.schedule;

	let env: Record<string, string> = {};
	if (!input.buildOnly) {
		const url = input.custom[BACKUPS_URL_KEY];
		if (!url) throw new BackupsUrlMissing(stage);
		env = {
			BACKUPS_URL: url,
			BACKUPS_PREFIX: prefix,
			BACKUPS_DATABASES: JSON.stringify(
				databases.map(({ file, name }) => ({ file, name })),
			),
			BACKUPS_SCHEDULE: JSON.stringify(
				kind === 'cron'
					? {
							kind,
							minutes: input.backups.schedule.minutes,
							hours: input.backups.schedule.hours,
							days: input.backups.schedule.days,
							months: input.backups.schedule.months,
							weekdays: input.backups.schedule.weekdays,
						}
					: { kind, ...schedule },
			),
			BACKUPS_MAX_GAP_SECONDS: String(input.backups.maxGapSeconds),
			PGHOST: 'postgres',
			PGPORT: '5432',
			PGUSER: login.user,
			PGPASSWORD: login.password,
			...(input.telemetry?.OTEL_EXPORTER_OTLP_ENDPOINT
				? {
						OTEL_EXPORTER_OTLP_ENDPOINT:
							input.telemetry.OTEL_EXPORTER_OTLP_ENDPOINT,
						...(input.telemetry.OTEL_EXPORTER_OTLP_HEADERS
							? {
									OTEL_EXPORTER_OTLP_HEADERS:
										input.telemetry.OTEL_EXPORTER_OTLP_HEADERS,
								}
							: {}),
						OTEL_SERVICE_NAME: BACKUPS_SERVICE,
					}
				: {}),
		};
	}

	return {
		backups: input.backups,
		databases,
		prefix,
		from,
		image: `${input.project}-backups:pg${version}-${hash}`,
		files: { Dockerfile: dockerfile, 'backup.mjs': script },
		login,
		readOnly,
		env,
	};
}

/** The service in the stack's compose file. */
export function backupsService(backups: StackBackups, envFiles: boolean) {
	return {
		image: backups.image,
		// Built on the server from two files; there is nothing to pull.
		build: { context: `./${BACKUPS_SERVICE}`, dockerfile: 'Dockerfile' },
		pull_policy: 'build' as const,
		restart: 'unless-stopped',
		...(envFiles
			? {
					env_file: [
						{ path: `./${BACKUPS_SERVICE}.env`, format: 'raw' as const },
					],
				}
			: {}),
		depends_on: { postgres: { condition: 'service_healthy' as const } },
		healthcheck: {
			test: ['CMD', 'node', RUNNER_PATH, 'health'],
			interval: '1m',
			timeout: '10s',
			retries: 3,
			start_period: '30s',
		},
	};
}

/**
 * The backups role, created and kept: able to sign in and read every
 * database, and nothing else. None when it signs in as the superuser.
 */
export function backupsRoleStatements(backups: StackBackups): Statement[] {
	if (!backups.readOnly) return [];
	const role = quoteIdentifier(backups.login.user);
	const password = `'${backups.login.password.replace(/'/g, "''")}'`;
	return [
		{
			id: BACKUPS_SERVICE,
			describe: `role ${backups.login.user}`,
			exists: {
				sql: 'SELECT 1 FROM pg_roles WHERE rolname = $1',
				values: [backups.login.user],
			},
			create: `CREATE ROLE ${role} LOGIN PASSWORD ${password}`,
		},
		{
			id: BACKUPS_SERVICE,
			describe: `role ${backups.login.user}: its password`,
			create: `ALTER ROLE ${role} WITH LOGIN PASSWORD ${password}`,
		},
		{
			id: BACKUPS_SERVICE,
			describe: `role ${backups.login.user}: read every database`,
			create: `GRANT pg_read_all_data TO ${role}`,
		},
	];
}
