import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { promisify } from 'node:util';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

/**
 * Stage names, checked against the declared stages.
 *
 * The augmentation is global to a program, so the declared case and the
 * fallback cannot share one: each is a small project in a directory of its
 * own, compiled by the real `tsc` against this package's source. The declared
 * one holds `.gkm/stages.d.ts` exactly as gkm writes it; the fallback has none.
 */

const run = promisify(execFile);

const PACKAGE = resolve(import.meta.dirname, '../..');
const REPO = resolve(PACKAGE, '../..');
const TSC = join(
	dirname(createRequire(import.meta.url).resolve('typescript/package.json')),
	'bin',
	'tsc',
);

/** What `gkm` writes for `stages: { local: 'dev', deployed: ['staging', 'prod'] }`. */
const GENERATED = `// Generated by gkm from the \`stages\` in gkm.config.ts — do not edit.
export {};

declare module '@geekmidas/constructs' {
	interface Stages {
		local: 'dev';
		deployed: 'staging' | 'prod';
	}
}
`;

/** A credentials schema without a validation library to resolve. */
const PREAMBLE = `import type {
	AnyStage,
	DeployedStage,
	LocalStage,
	SeedContext,
} from '@geekmidas/constructs';
import { ExternalApi } from '@geekmidas/constructs/external-api';
import type { StandardSchemaV1 } from '@standard-schema/spec';

type Equal<A, B> =
	(<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2
		? true
		: false;
function assertType<T extends true>(): T | undefined {
	return undefined;
}

const credentials: StandardSchemaV1<object> = {
	'~standard': {
		version: 1,
		vendor: 'probe',
		validate: (value) => ({ value: value as object }),
	},
};

export function api(url: ConstructorParameters<typeof ExternalApi>[1]['url']) {
	return new ExternalApi('Probe', { url, credentials, client: () => url });
}
`;

describe('typed stages', { timeout: 60_000 }, () => {
	let dir: string;

	beforeEach(async () => {
		dir = await mkdtemp(join(tmpdir(), 'gkm-stages-'));
		await writeFile(
			join(dir, 'tsconfig.json'),
			JSON.stringify({
				extends: join(PACKAGE, 'tsconfig.json'),
				compilerOptions: {
					noEmit: true,
					composite: false,
					declaration: false,
					declarationMap: false,
					rootDir: '/',
					typeRoots: [
						join(PACKAGE, 'node_modules/@types'),
						join(REPO, 'node_modules/@types'),
					],
					paths: {
						'@geekmidas/constructs': [join(PACKAGE, 'src/index.ts')],
						'@geekmidas/constructs/*': [join(PACKAGE, 'src/*.ts')],
						'@standard-schema/spec': [
							join(REPO, 'node_modules/@standard-schema/spec'),
						],
					},
				},
				// Named: a wildcard never matches a dot folder.
				include: ['check.ts', '.gkm/stages.d.ts'],
			}),
		);
	});

	afterEach(async () => {
		await rm(dir, { recursive: true, force: true });
	});

	/** Compile `check.ts`; the type errors, one per line, or nothing. */
	async function typecheck(check: string): Promise<string[]> {
		await writeFile(join(dir, 'check.ts'), `${PREAMBLE}\n${check}`);
		const { NODE_OPTIONS: _, ...env } = process.env;
		const result = await run(
			process.execPath,
			[TSC, '-p', dir, '--pretty', 'false'],
			{ env },
		).catch((error: { stdout: string }) => ({ stdout: error.stdout }));
		return result.stdout.split('\n').filter((line) => line.includes('error'));
	}

	describe('with .gkm/stages.d.ts', () => {
		beforeEach(async () => {
			await mkdir(join(dir, '.gkm'));
			await writeFile(join(dir, '.gkm/stages.d.ts'), GENERATED);
		});

		it('is the declared names', async () => {
			const errors = await typecheck(`
assertType<Equal<LocalStage, 'dev'>>();
assertType<Equal<DeployedStage, 'staging' | 'prod'>>();
assertType<Equal<AnyStage, 'dev' | 'test' | 'staging' | 'prod'>>();
`);

			expect(errors).toEqual([]);
		});

		it('hands a seed the union as its `stage`', async () => {
			const errors = await typecheck(`
assertType<Equal<SeedContext['stage'], 'dev' | 'test' | 'staging' | 'prod'>>();

export async function seed(_db: unknown, { stage }: SeedContext) {
	if (stage === 'prod') return;
	// @ts-expect-error — 'prodution' is no stage, so this branch never runs
	if (stage === 'prodution') return;
}
`);

			expect(errors).toEqual([]);
		});

		it("refuses an ExternalApi url keyed by a stage that isn't declared", async () => {
			const errors = await typecheck(`
api('https://every.example');
api({ prod: 'https://live.example', dev: 'https://local.example' });
api({ staging: 'https://sandbox.example', default: 'https://live.example' });
api({ prodution: 'https://live.example', default: 'https://sandbox.example' });
`);

			expect(errors).toHaveLength(1);
			expect(errors[0]).toMatch(
				/check\.ts\(\d+,\d+\): error TS\d+:.*prodution/,
			);
		});
	});

	describe('without it', () => {
		it('is string, so nothing needs the file to compile', async () => {
			const errors = await typecheck(`
assertType<Equal<LocalStage, string>>();
assertType<Equal<DeployedStage, string>>();
assertType<Equal<AnyStage, string>>();
assertType<Equal<SeedContext['stage'], string>>();

api({ prodution: 'https://live.example', default: 'https://sandbox.example' });
`);

			expect(errors).toEqual([]);
		});
	});
});
