/**
 * The compose document a plan implies.
 *
 * The third declaration of the same containers disappears here: today a
 * `services: ['postgres','minio']` block is kept in step with the code by hand,
 * which is the triplication this design exists to remove, in the one place you
 * touch every day. A `database` implies Postgres; the list is derived.
 *
 * Returns an object rather than a string for the same reason `plan` is pure —
 * what should exist is asserted as data, and turning it into YAML is one line at
 * the edge.
 *
 * What stays config is unchanged: images and versions are pinned explicitly, and
 * a container no construct implies is still declared by hand. Neutral facts come
 * from the declaration, provider detail from config.
 */

import { stringify } from 'yaml';
import { DEFAULT_IMAGES, portsOf, postgresImage, volumeOf } from './containers';
import { EMULATOR_CREDENTIALS, EMULATOR_REGION } from './emulator';
import type { Plan } from './plan';
import type { PortAssignments } from './ports';

/** A compose service definition — as much of the schema as is emitted here. */
export interface ComposeService {
	image: string;
	/** An app is built from its generated Dockerfile; a container is pulled. */
	build?: { context: string; dockerfile: string };
	/** Behind a profile, so starting the containers does not start the apps. */
	profiles?: string[];
	restart?: string;
	entrypoint?: string;
	command?: string;
	ports?: string[];
	environment?: Record<string, string>;
	volumes?: string[];
	depends_on?: string[];
	healthcheck?: {
		test: string[];
		interval: string;
		timeout: string;
		retries: number;
		start_period?: string;
	};
	extra_hosts?: string[];
}

export interface ComposeFile {
	name: string;
	services: Record<string, ComposeService>;
	volumes?: Record<string, Record<string, never>>;
}

/** The credential every derived container is brought up with locally. */
const LOCAL_USER = 'geekmidas';

/**
 * The token the local cache accepts.
 *
 * Fixed rather than generated: it is only ever reachable on a port this project
 * published, and the URL that carries it is derived, so nothing is made safer
 * by making it unguessable and a stable one keeps `redis-cli` sessions working.
 */
const LOCAL_TOKEN = 'geekmidas';

export interface ComposeOptions {
	/** Names the compose project, which is what isolates it from other stacks. */
	project: string;
	/** Ports assigned by `allocate`, keyed by port key — see `portKeys`. */
	ports: PortAssignments;
	/** App services to write beside the containers — see `reconcile/apps.ts`. */
	apps?: Readonly<Record<string, ComposeService>>;
}

/**
 * Build the compose document for a plan.
 *
 * Every container is published on its assigned port, never on the image's
 * default: the point of allocation is that two projects can run at once, and
 * one container publishing 5432 puts that back.
 */
export function composeFor(plan: Plan, options: ComposeOptions): ComposeFile {
	const services: Record<string, ComposeService> = {};
	const volumes: Record<string, Record<string, never>> = {};

	for (const container of [...plan.containers].sort()) {
		// A declared version beats the default image, so the container a
		// developer runs is the major the declaration names — and the same one a
		// deploy provisions. An image pin is the project's own
		// `docker-compose.yml`, merged over this file, and wins over both.
		const declared =
			container === 'postgres'
				? plan.resources.find((r) => r.version)?.version
				: undefined;

		const fake = plan.fakes?.[container];
		const image = declared
			? postgresImage(declared)
			: (fake?.image ?? DEFAULT_IMAGES[container]);
		if (!image) throw new UnknownContainer(container);

		const published = publish(container, options.ports, plan.fakes);
		services[container] = fake
			? // An external API's fake: the provider's image, as it ships. It has
				// no volume — a fake keeps nothing worth keeping — and no
				// healthcheck, so running is what ready means.
				{ image, restart: 'unless-stopped', ports: published }
			: define(container, image, published);

		const volume = volumeOf(container);
		if (volume) volumes[volume] = {};
	}

	return {
		// Compose derives a project name from the directory otherwise, so two
		// checkouts of the same repo would fight over one set of containers.
		name: options.project,
		services: { ...services, ...options.apps },
		...(Object.keys(volumes).length ? { volumes } : {}),
	};
}

/** Render a compose document as the file it becomes. */
export function toYaml(file: ComposeFile): string {
	return `# Generated by gkm from the construct manifest — do not edit.
# Containers are derived from what the app declares. Image pins and anything
# no construct implies go in your own docker-compose.yml, which is merged over
# this file and wins:
#
#   docker compose -f docker-compose.constructs.yml -f docker-compose.yml …
#
# "gkm dev" and "gkm test" start the containers. The apps sit behind the
# "apps" profile: run "gkm setup", then
#   docker compose -f docker-compose.constructs.yml --profile apps up --build
${stringify(file, { lineWidth: 0 })}`;
}

/** A container with no image, from config or from the defaults. */
export class UnknownContainer extends Error {
	/** The container that could not be resolved. */
	readonly container: string;
	/** The containers that have a default, so the caller can see the set. */
	readonly known: readonly string[] = Object.keys(DEFAULT_IMAGES).sort();

	constructor(container: string) {
		super('No image is known for this container; pin one in config');
		this.name = 'UnknownContainer';
		this.container = container;
	}
}

/** One container's definition, published on the port it was assigned. */
function define(
	container: string,
	image: string,
	published: string[],
): ComposeService {
	switch (container) {
		case 'postgres':
			return {
				image,
				restart: 'unless-stopped',
				ports: published,
				environment: {
					POSTGRES_USER: LOCAL_USER,
					POSTGRES_PASSWORD: LOCAL_USER,
					// The cluster's own database. Every declared database is created
					// inside this cluster by the applier, not by the image.
					POSTGRES_DB: LOCAL_USER,
				},
				// One mount at the parent, not at `data`: the 18 image keeps its
				// cluster in a version-named subdirectory and refuses to start when
				// something is mounted over the legacy path. Mounting the parent is
				// also what makes the next major bump a `pg_upgrade --link` rather
				// than a new volume.
				volumes: ['postgres-data:/var/lib/postgresql'],
				healthcheck: {
					test: ['CMD-SHELL', `pg_isready -U ${LOCAL_USER}`],
					interval: '5s',
					timeout: '3s',
					retries: 10,
					start_period: '10s',
				},
			};

		case 'minio':
			return {
				image,
				restart: 'unless-stopped',
				ports: published,
				environment: {
					MINIO_ROOT_USER: LOCAL_USER,
					MINIO_ROOT_PASSWORD: LOCAL_USER,
				},
				// No bucket is created here: buckets are planned resources, and
				// creating them in the entrypoint would put their names back in the
				// compose file — the declaration this change removes.
				command: 'server --console-address ":9001" /data',
				volumes: ['minio-data:/data'],
				healthcheck: {
					test: ['CMD', 'mc', 'ready', 'local'],
					interval: '10s',
					timeout: '5s',
					retries: 5,
					start_period: '10s',
				},
			};

		case 'caddy':
			return {
				image,
				restart: 'unless-stopped',
				ports: published,
				// Relative to this file, which is at the project root, so the
				// mount resolves into `.gkm/` wherever the project lives.
				volumes: [
					'./.gkm/Caddyfile:/etc/caddy/Caddyfile:ro',
					// A directory, not a file: every stage writes its own routes into
					// it, so `gkm test` cannot delete what `gkm dev` is serving.
					'./.gkm/caddy-sites:/etc/caddy/sites:ro',
					'caddy-data:/data',
				],
				// A surface and a site are processes on the *host*, not containers,
				// so the edge has to leave Docker's network to reach them. Docker
				// Desktop resolves this name already; on Linux it needs saying.
				extra_hosts: ['host.docker.internal:host-gateway'],
				healthcheck: {
					test: ['CMD', 'caddy', 'version'],
					interval: '10s',
					timeout: '5s',
					retries: 5,
				},
			};

		case 'mailpit':
			return {
				image,
				restart: 'unless-stopped',
				ports: published,
				environment: {
					// Accept mail from anything on this network. The URL carries no
					// credentials locally, which is what the parser's optional `auth`
					// exists for.
					MP_SMTP_AUTH_ACCEPT_ANY: '1',
					MP_SMTP_AUTH_ALLOW_INSECURE: '1',
				},
				healthcheck: {
					test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:8025'],
					interval: '10s',
					timeout: '5s',
					retries: 5,
				},
			};

		case 'redis':
			return {
				image,
				restart: 'unless-stopped',
				ports: published,
				volumes: ['redis-data:/data'],
				healthcheck: {
					test: ['CMD', 'redis-cli', 'ping'],
					interval: '5s',
					timeout: '3s',
					retries: 5,
				},
			};

		case 'redis-http':
			return {
				image,
				restart: 'unless-stopped',
				ports: published,
				environment: {
					SRH_MODE: 'env',
					SRH_TOKEN: LOCAL_TOKEN,
					// The Redis beside it, by compose service name — the one address
					// in this file that is not published, because nothing outside the
					// network speaks to it.
					SRH_CONNECTION_STRING: 'redis://redis:6379',
				},
				depends_on: ['redis'],
				healthcheck: {
					// 127.0.0.1, not localhost: the proxy binds IPv4 only, and
					// `localhost` resolves to ::1 first inside the container — which
					// is a health check that never passes and a container that never
					// comes up.
					test: [
						'CMD',
						'wget',
						'-q',
						'-O',
						'/dev/null',
						'http://127.0.0.1:80/',
					],
					interval: '5s',
					timeout: '3s',
					retries: 10,
				},
			};

		case 'rabbitmq':
			return {
				image,
				restart: 'unless-stopped',
				ports: published,
				environment: {
					RABBITMQ_DEFAULT_USER: LOCAL_USER,
					RABBITMQ_DEFAULT_PASS: LOCAL_USER,
				},
				volumes: ['rabbitmq-data:/var/lib/rabbitmq'],
				healthcheck: {
					test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping'],
					interval: '10s',
					timeout: '5s',
					retries: 5,
				},
			};

		case 'localstack':
			return {
				image,
				restart: 'unless-stopped',
				ports: published,
				environment: {
					AWS_DEFAULT_REGION: EMULATOR_REGION,
					AWS_ACCESS_KEY_ID: EMULATOR_CREDENTIALS.accessKeyId,
					AWS_SECRET_ACCESS_KEY: EMULATOR_CREDENTIALS.secretAccessKey,
				},
				volumes: ['localstack-data:/var/lib/localstack'],
				healthcheck: {
					// Bash, not curl: the floci image ships no curl, so a curl check
					// never passes and `--wait` fails every start. A TCP connect is
					// the fact a waiter needs — the gateway binds the port once its
					// HTTP server is up — and the repo's own compose file does the
					// same.
					test: ['CMD', 'bash', '-c', 'exec 3<>/dev/tcp/localhost/4566'],
					interval: '10s',
					timeout: '5s',
					retries: 5,
					start_period: '10s',
				},
			};

		default:
			throw new UnknownContainer(container);
	}
}

/**
 * The published port mappings for a container.
 *
 * Every port is looked up by its own key rather than being derived as an offset
 * from the container's first, so MinIO's console cannot land on whatever was
 * allocated to the next container.
 */
function publish(
	container: string,
	ports: PortAssignments,
	fakes?: Plan['fakes'],
): string[] {
	return portsOf(container, fakes).map((port) => {
		const assigned = ports[port.key];
		if (assigned === undefined) throw new UnassignedPort(port.key);

		return `${assigned}:${port.inside}`;
	});
}

/** A planned port that allocation never assigned. */
export class UnassignedPort extends Error {
	/** The port key that went unassigned, e.g. `minio-console`. */
	readonly key: string;

	constructor(key: string) {
		super('No port was assigned for this container port');
		this.name = 'UnassignedPort';
		this.key = key;
	}
}
