/**
 * The manifest, written out as a module.
 *
 * Discovery imports the application's own code — that is how it finds
 * constructs — so anything calling it evaluates the whole runtime graph: React
 * email templates, database clients, modules that read env at import time. That
 * is fine inside `gkm dev`, which is already running the app. It is not fine
 * inside a deploy config, where it fails on the first thing the deploy toolchain
 * does not expect and would keep failing on the next.
 *
 * So discovery happens once, in the build, and everything downstream reads what
 * it wrote. The same split `RestApi` makes by naming a routes glob rather than
 * importing route modules.
 *
 * A module rather than JSON, because a manifest is not just data to this
 * codebase — `as const satisfies ConstructManifest` is what keeps every id,
 * kind and provided key a *literal*, so `IdsOf`, `ProvidedKeys` and the rest
 * can select out of it. `JSON.parse` returns `any` and gives all of that up.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { ConstructManifest } from '@geekmidas/manifest';

/** Where the build writes it, relative to the app root. */
export const MANIFEST_PATH = '.gkm/manifest.ts';

/**
 * The manifest as TypeScript source.
 *
 * Pure, so what gets written can be asserted without touching a filesystem.
 */
export function manifestModule(manifest: ConstructManifest): string {
	return `${HEADER}
export const manifest = ${serialise(manifest)} as const satisfies ConstructManifest;

/** Every construct id in this app. */
export type Ids = IdsOf<typeof manifest>;

/** Every environment key its constructs provide. */
export type ProvidedKeys = AllProvidedKeys<typeof manifest>;

export default manifest;
`;
}

/** Write it where the deploy config expects to import it from. */
export async function writeManifestModule(
	manifest: ConstructManifest,
	appRoot: string,
): Promise<string> {
	const path = join(appRoot, MANIFEST_PATH);

	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, manifestModule(manifest), 'utf8');

	return path;
}

const HEADER = `// Generated by \`gkm build\`. Do not edit.
//
// Discovery imports application code, so it runs once here rather than in every
// consumer — a deploy config that discovered for itself would evaluate the whole
// runtime graph inside its own toolchain. This is the result, as literals.

import type {
	AllProvidedKeys,
	ConstructManifest,
	IdsOf,
} from '@geekmidas/manifest';
`;

/**
 * JSON, re-indented with tabs and with keys left unquoted where they can be.
 *
 * Cosmetic, and worth it: this file is read by people trying to work out what
 * their app declares, and a wall of quoted keys reads as output rather than as
 * something anyone is expected to understand.
 */
function serialise(manifest: ConstructManifest): string {
	return JSON.stringify(manifest, null, '\t')
		.replace(/^(\t*)"([A-Za-z_$][\w$]*)":/gm, '$1$2:')
		.replace(/"/g, "'");
}
