/**
 * @vitest-environment jsdom
 *
 * Type inference test for mutation hooks with complex paths.
 * This mirrors the structure generated by `gkm openapi` to verify
 * that FilteredRequestConfig resolves correctly (not `never`).
 */
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { renderHook, waitFor } from '@testing-library/react';
import { HttpResponse, http } from 'msw';
// biome-ignore lint/style/useImportType: needed for JSX
import React, { createElement } from 'react';
import { beforeEach, describe, expect, it } from 'vitest';
import { createEndpointHooks } from '../endpoint-hooks';
import type { TypedApiFunction } from '../types';
import { server } from './setup';

// ============================================================
// Paths that mirror a real generated openapi.ts structure
// ============================================================
interface GeneratedPaths {
	'/account/profile': {
		post: {
			requestBody: {
				content: {
					'application/json': { email: string; name: string };
				};
			};
			responses: {
				200: {
					content: {
						'application/json': Record<string, unknown>;
					};
				};
			};
		};
		get: {
			responses: {
				200: {
					content: {
						'application/json': {
							id: string;
							email: string;
							name: string;
						} | null;
					};
				};
			};
		};
	};
	'/chats/{chatId}/participants': {
		parameters: {
			path: { chatId: string };
		};
		post: {
			requestBody: {
				content: {
					'application/json': { userId: string; role: 'Owner' | 'Member' };
				};
			};
			responses: {
				200: {
					content: {
						'application/json': {
							id: string;
							chatId: string;
							userId: string;
							role: string;
						};
					};
				};
			};
		};
	};
	'/chats': {
		post: {
			requestBody: {
				content: {
					'application/json': { type: string; name?: string };
				};
			};
			responses: {
				200: {
					content: {
						'application/json': { id: string; type: string; name: string };
					};
				};
			};
		};
		get: {
			parameters: {
				query: { cursor?: string; limit: number };
			};
			responses: {
				200: {
					content: {
						'application/json': {
							data: Array<{ id: string; name: string }>;
							hasMore: boolean;
						};
					};
				};
			};
		};
	};
	'/chats/{id}': {
		parameters: {
			path: { id: string };
		};
		delete: {
			responses: {
				200: {
					content: {
						'application/json': { success: boolean };
					};
				};
			};
		};
		get: {
			responses: {
				200: {
					content: {
						'application/json': { id: string; name: string };
					};
				};
			};
		};
		patch: {
			requestBody: {
				content: {
					'application/json': { name?: string; status?: string };
				};
			};
			responses: {
				200: {
					content: {
						'application/json': { id: string; name: string; status: string };
					};
				};
			};
		};
	};
	'/chats/{chatId}/leave': {
		parameters: {
			path: { chatId: string };
		};
		post: {
			responses: {
				200: {
					content: {
						'application/json': { success: boolean };
					};
				};
			};
		};
	};
}

// ============================================================
// Mock fetcher
// ============================================================
function createMockFetcher(): TypedApiFunction<GeneratedPaths> {
	return async (endpoint: string, config?: any) => {
		const [method, path] = endpoint.split(' ');
		let url = `https://api.example.com${path}`;

		if (config?.params) {
			for (const [key, value] of Object.entries(config.params)) {
				url = url.replace(`{${key}}`, value as string);
			}
		}

		const response = await fetch(url, {
			method,
			headers: { 'Content-Type': 'application/json', ...config?.headers },
			body: config?.body ? JSON.stringify(config.body) : undefined,
		});

		return response.json();
	};
}

function createWrapper() {
	const queryClient = new QueryClient({
		defaultOptions: { queries: { retry: false } },
	});
	return ({ children }: { children: React.ReactNode }) =>
		createElement(QueryClientProvider, { client: queryClient }, children);
}

// ============================================================
// Tests
// ============================================================
describe('mutation type inference with generated paths', () => {
	beforeEach(() => {
		server.use(
			http.post('https://api.example.com/account/profile', async ({ request }) => {
				const body = (await request.json()) as any;
				return HttpResponse.json({ id: '1', ...body });
			}),
			http.post('https://api.example.com/chats', async ({ request }) => {
				const body = (await request.json()) as any;
				return HttpResponse.json({ id: 'chat-1', type: body.type, name: body.name ?? 'New Chat' });
			}),
			http.post('https://api.example.com/chats/:chatId/participants', async ({ params, request }) => {
				const body = (await request.json()) as any;
				return HttpResponse.json({
					id: 'p-1',
					chatId: params.chatId,
					userId: body.userId,
					role: body.role,
				});
			}),
			http.delete('https://api.example.com/chats/:id', () => {
				return HttpResponse.json({ success: true });
			}),
			http.patch('https://api.example.com/chats/:id', async ({ params, request }) => {
				const body = (await request.json()) as any;
				return HttpResponse.json({
					id: params.id,
					name: body.name ?? 'Chat',
					status: body.status ?? 'Active',
				});
			}),
			http.post('https://api.example.com/chats/:chatId/leave', () => {
				return HttpResponse.json({ success: true });
			}),
		);
	});

	it('should resolve body-only mutation args (POST /chats)', async () => {
		const hooks = createEndpointHooks<GeneratedPaths>(createMockFetcher());
		const { result } = renderHook(() => hooks.useMutation('POST /chats'), {
			wrapper: createWrapper(),
		});

		// If args were `never`, this call would be a type error
		result.current.mutate({ body: { type: 'GeneralChat', name: 'Test' } });

		await waitFor(() => expect(result.current.isSuccess).toBe(true));
		expect(result.current.data).toMatchObject({ id: 'chat-1', type: 'GeneralChat' });
	});

	it('should resolve body-only mutation args (POST /account/profile)', async () => {
		const hooks = createEndpointHooks<GeneratedPaths>(createMockFetcher());
		const { result } = renderHook(() => hooks.useMutation('POST /account/profile'), {
			wrapper: createWrapper(),
		});

		result.current.mutate({ body: { email: 'test@test.com', name: 'Test' } });

		await waitFor(() => expect(result.current.isSuccess).toBe(true));
		expect(result.current.data).toMatchObject({ email: 'test@test.com' });
	});

	it('should resolve params+body mutation args (POST /chats/{chatId}/participants)', async () => {
		const hooks = createEndpointHooks<GeneratedPaths>(createMockFetcher());
		const { result } = renderHook(
			() => hooks.useMutation('POST /chats/{chatId}/participants'),
			{ wrapper: createWrapper() },
		);

		result.current.mutate({
			params: { chatId: 'chat-1' },
			body: { userId: 'user-1', role: 'Member' },
		});

		await waitFor(() => expect(result.current.isSuccess).toBe(true));
		expect(result.current.data).toMatchObject({ chatId: 'chat-1', userId: 'user-1' });
	});

	it('should resolve params-only mutation args (DELETE /chats/{id})', async () => {
		const hooks = createEndpointHooks<GeneratedPaths>(createMockFetcher());
		const { result } = renderHook(() => hooks.useMutation('DELETE /chats/{id}'), {
			wrapper: createWrapper(),
		});

		result.current.mutate({ params: { id: 'chat-1' } });

		await waitFor(() => expect(result.current.isSuccess).toBe(true));
		expect(result.current.data).toEqual({ success: true });
	});

	it('should resolve params+body mutation args (PATCH /chats/{id})', async () => {
		const hooks = createEndpointHooks<GeneratedPaths>(createMockFetcher());
		const { result } = renderHook(() => hooks.useMutation('PATCH /chats/{id}'), {
			wrapper: createWrapper(),
		});

		result.current.mutate({
			params: { id: 'chat-1' },
			body: { name: 'Renamed Chat' },
		});

		await waitFor(() => expect(result.current.isSuccess).toBe(true));
		expect(result.current.data).toMatchObject({ id: 'chat-1', name: 'Renamed Chat' });
	});

	it('should resolve params-only POST mutation args (POST /chats/{chatId}/leave)', async () => {
		const hooks = createEndpointHooks<GeneratedPaths>(createMockFetcher());
		const { result } = renderHook(
			() => hooks.useMutation('POST /chats/{chatId}/leave'),
			{ wrapper: createWrapper() },
		);

		// POST with only path params, no body
		result.current.mutate({ params: { chatId: 'chat-1' } });

		await waitFor(() => expect(result.current.isSuccess).toBe(true));
		expect(result.current.data).toEqual({ success: true });
	});
});
