/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module 'sst' {
	export interface Resource {
		Api: {
			cookieDomain: string;
			trustedOrigins: string;
			type: 'sst.aws.ApiGatewayV2';
			url: string;
		};
		Auth: {
			cookieDomain: string;
			trustedOrigins: string;
			type: 'sst.aws.ApiGatewayV2';
			url: string;
		};
		AuthSecret: {
			type: 'sst.sst.Secret';
			value: string;
		};
		Emails: {
			arn: string;
			publisherConnectionString: string;
			type: 'sst.aws.Queue';
			url: string;
		};
		KitchenSink: {
			clusterArn: string;
			database: string;
			host: string;
			password: string;
			port: number;
			reader: string;
			secretArn: string;
			type: 'sst.aws.Aurora';
			url: string;
			username: string;
		};
		KitchenSinkBootstrap: {
			name: string;
			type: 'sst.aws.Function';
		};
		Payments: {
			credential: string;
			type: 'sst.sst.Secret';
			value: string;
		};
		Uploads: {
			name: string;
			type: 'sst.aws.Bucket';
			url: string;
		};
		UploadsServer: {
			type: 'sst.aws.Router';
			url: string;
		};
		Users: {
			arn: string;
			publisherConnectionString: string;
			type: 'sst.aws.SnsTopic';
		};
		Vpc: {
			type: 'sst.aws.Vpc';
		};
		Web: {
			type: 'sst.aws.StaticSite';
			url: string;
		};
	}
}

import 'sst';
export {};
