import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { openapiCommand } from '../openapi';
import {
  cleanupDir,
  createMockEndpointFile,
  createTempDir,
  createTestFile,
} from './test-helpers';

describe('OpenAPI Generation', () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await createTempDir('openapi-test-');
  });

  afterEach(async () => {
    await cleanupDir(tempDir);
    vi.restoreAllMocks();
  });

  describe('openapiCommand - TypeScript output (default)', () => {
    it('should generate TypeScript module by default', async () => {
      await createMockEndpointFile(
        tempDir,
        'getUser.ts',
        'getUser',
        '/users/:id',
        'GET',
      );

      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'openapi.ts');

      await openapiCommand({ output: outputPath, cwd: tempDir });

      expect(existsSync(outputPath)).toBe(true);

      const content = await readFile(outputPath, 'utf-8');

      expect(content).toContain('// Auto-generated by @geekmidas/cli');
      expect(content).toContain('export const securitySchemes');
      expect(content).toContain('export const endpointAuth');
      expect(content).toContain('export interface paths');
    });

    it('should include endpoint auth map', async () => {
      await createMockEndpointFile(
        tempDir,
        'getUser.ts',
        'getUser',
        '/users/:id',
        'GET',
      );

      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'openapi.ts');

      await openapiCommand({ output: outputPath, cwd: tempDir });

      const content = await readFile(outputPath, 'utf-8');

      expect(content).toContain('endpointAuth');
      expect(content).toContain("'GET /users/{id}'");
    });
  });

  describe('openapiCommand - JSON output (legacy)', () => {
    it('should generate JSON OpenAPI spec with --json flag', async () => {
      await createMockEndpointFile(
        tempDir,
        'getUser.ts',
        'getUser',
        '/users/:id',
        'GET',
      );

      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'openapi.json');

      await openapiCommand({ output: outputPath, json: true, cwd: tempDir });

      expect(existsSync(outputPath)).toBe(true);

      const content = await readFile(outputPath, 'utf-8');
      const spec = JSON.parse(content);

      expect(spec).toHaveProperty('openapi');
      expect(spec).toHaveProperty('info');
      expect(spec.info.title).toBe('API Documentation');
      expect(spec).toHaveProperty('paths');
      expect(Object.keys(spec.paths).length).toBeGreaterThan(0);
    });

    it('should handle no endpoints found', async () => {
      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/nonexistent/**/*.ts`],
        }),
      );

      const consoleSpy = vi.spyOn(console, 'log');

      await openapiCommand({
        output: join(tempDir, 'openapi.json'),
        json: true,
        cwd: tempDir,
      });

      expect(consoleSpy).toHaveBeenCalledWith('No valid endpoints found');
    });

    it('should generate spec with multiple endpoints', async () => {
      await createMockEndpointFile(
        tempDir,
        'getUsers.ts',
        'getUsers',
        '/users',
        'GET',
      );
      await createMockEndpointFile(
        tempDir,
        'createUser.ts',
        'createUser',
        '/users',
        'POST',
      );
      await createMockEndpointFile(
        tempDir,
        'deleteUser.ts',
        'deleteUser',
        '/users/:id',
        'DELETE',
      );

      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'openapi.json');

      await openapiCommand({ output: outputPath, json: true, cwd: tempDir });

      const content = await readFile(outputPath, 'utf-8');
      const spec = JSON.parse(content);

      expect(Object.keys(spec.paths).length).toBeGreaterThanOrEqual(1);
    });

    it('should create output directory if it does not exist', async () => {
      await createMockEndpointFile(
        tempDir,
        'endpoint.ts',
        'testEndpoint',
        '/test',
        'GET',
      );

      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'nested', 'dir', 'openapi.json');

      await openapiCommand({ output: outputPath, json: true, cwd: tempDir });

      expect(existsSync(outputPath)).toBe(true);
    });

    it('should include API metadata in spec', async () => {
      await createMockEndpointFile(
        tempDir,
        'endpoint.ts',
        'testEndpoint',
        '/test',
        'GET',
      );

      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'openapi.json');

      await openapiCommand({ output: outputPath, json: true, cwd: tempDir });

      const content = await readFile(outputPath, 'utf-8');
      const spec = JSON.parse(content);

      expect(spec.info).toEqual({
        title: 'API Documentation',
        version: '1.0.0',
        description: 'Auto-generated API documentation from endpoints',
      });
    });

    it('should log generation success for JSON', async () => {
      // Create endpoint
      await createMockEndpointFile(
        tempDir,
        'endpoint.ts',
        'testEndpoint',
        '/test',
        'GET',
      );

      // Create config
      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'openapi.json');
      const consoleSpy = vi.spyOn(console, 'log');

      await openapiCommand({ output: outputPath, json: true, cwd: tempDir });

      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining('OpenAPI JSON spec generated'),
      );
      expect(consoleSpy).toHaveBeenCalledWith(expect.stringContaining('Found'));
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining('endpoints'),
      );
    });

    it('should throw error when config loading fails', async () => {
      // No config file created
      await expect(
        openapiCommand({ json: true, cwd: tempDir }),
      ).rejects.toThrow(/OpenAPI generation failed/);
    });

    it('should throw error for invalid TypeScript files', async () => {
      // Create invalid TS file
      await createTestFile(
        tempDir,
        'invalid.ts',
        'this is not valid typescript {[}]',
      );

      // Create config
      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      // Should throw error for syntax errors
      await expect(
        openapiCommand({
          output: join(tempDir, 'openapi.json'),
          json: true,
          cwd: tempDir,
        }),
      ).rejects.toThrow(/OpenAPI generation failed/);
    });

    it('should generate valid JSON format', async () => {
      // Create endpoint
      await createMockEndpointFile(
        tempDir,
        'endpoint.ts',
        'testEndpoint',
        '/test',
        'GET',
      );

      // Create config
      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'openapi.json');

      await openapiCommand({ output: outputPath, json: true, cwd: tempDir });

      const content = await readFile(outputPath, 'utf-8');

      // Should be valid JSON and properly formatted
      expect(() => JSON.parse(content)).not.toThrow();
      expect(content).toContain('\n'); // Formatted with indentation
    });

    it('should handle endpoints with complex schemas', async () => {
      // Create endpoint with complex schema
      const complexEndpointContent = `
import { e } from '@geekmidas/constructs/endpoints';
import { z } from 'zod';

export const complexEndpoint = e
  .post('/complex')
  .body(z.object({
    user: z.object({
      name: z.string(),
      email: z.string().email(),
      age: z.number().optional(),
    }),
    tags: z.array(z.string()),
  }))
  .output(z.object({
    id: z.string(),
    status: z.enum(['active', 'inactive']),
  }))
  .handle(async () => ({ id: '123', status: 'active' as const }));
`;

      await createTestFile(tempDir, 'complex.ts', complexEndpointContent);

      // Create config
      await createTestFile(
        tempDir,
        'gkm.config.json',
        JSON.stringify({
          routes: [`${tempDir}/**/*.ts`],
        }),
      );

      const outputPath = join(tempDir, 'openapi.json');

      await openapiCommand({ output: outputPath, json: true, cwd: tempDir });

      const content = await readFile(outputPath, 'utf-8');
      const spec = JSON.parse(content);

      // Should have generated schema for complex types
      expect(spec.paths).toBeDefined();
    });
  });
});
