/**
 * The application under test: the same entry `gkm dev` runs, booted in process.
 *
 * `createApp()` builds the Hono app with the telescope middleware, the server
 * hooks (CORS and the mounted auth server), and every generated endpoint;
 * `start()` is what brings up the subscriber and queue pollers. So the suite
 * exercises the generated wiring rather than a second assembly written for
 * tests — which is the point, since the wiring is where the interesting bugs
 * have been.
 *
 * `start()` is given a `serve` that listens on nothing. Hono dispatches through
 * `app.request()`, so a port would only add a way for two runs to collide.
 */

import type { Hono } from 'hono';

/** A booted application, and the handles a spec needs to drive it. */
export interface Harness {
	/** Send a request the way the network would. */
	request(path: string, init?: RequestInit): Promise<Response>;
	/** The Hono app, for the rare assertion that needs it. */
	app: Hono;
}

let booted: Promise<Harness> | undefined;

/**
 * The one application instance the suite shares.
 *
 * One, because it holds the pollers: a second instance would drain the same
 * queue, and which of the two got a given message would decide whether a test
 * passed. `vitest.config.ts` keeps the suite single-threaded for the same
 * reason — this memo only covers one worker.
 */
export function harness(): Promise<Harness> {
	booted ??= boot();

	return booted;
}

async function boot(): Promise<Harness> {
	// Imported here rather than at module scope: the generated entry reads the
	// injected URLs while it evaluates, so it must not be imported before the
	// global setup has regenerated it.
	//
	// The specifier is a variable so `tsc` does not follow it. That is not a
	// dodge — the file is generated, it is regenerated by this suite's own
	// global setup, and typechecking it belongs to whatever generates it rather
	// than to the app that runs it. Resolving it statically also drags the
	// generated tree into the app's project, where its errors are reported
	// against a file nobody wrote.
	const entry = '../../../.gkm/server/app.js';
	const { createApp } = (await import(entry)) as {
		createApp: (
			app?: undefined,
			enableOpenApi?: boolean,
		) => Promise<{
			app: Hono;
			start: (options: {
				port?: number;
				serve: (app: Hono, port: number) => void;
			}) => Promise<void>;
		}>;
	};

	// OpenAPI off: it is generated at build time and serving it adds routes the
	// suite does not exercise.
	const { app, start } = await createApp(undefined, false);

	await start({
		port: 0,
		// Nothing listens. `start` exists here for its other half — bringing up
		// the subscriber and queue pollers, which is most of what these tests
		// are about.
		serve: () => {},
	});

	return {
		app,
		request: async (path, init) =>
			app.request(path.startsWith('http') ? path : `http://localhost${path}`, {
				...init,
			}),
	};
}

/** Send JSON and parse the answer, which is most of what a spec does. */
export async function sendJson<T = unknown>(
	method: 'POST' | 'PATCH' | 'PUT' | 'DELETE',
	path: string,
	body: unknown,
	init: RequestInit = {},
): Promise<{ status: number; body: T }> {
	const { request } = await harness();
	const response = await request(path, {
		...init,
		method,
		headers: {
			'content-type': 'application/json',
			...(init.headers as Record<string, string> | undefined),
		},
		body: JSON.stringify(body),
	});

	return { status: response.status, body: (await response.json()) as T };
}

export const postJson = <T = unknown>(
	path: string,
	body: unknown,
	init?: RequestInit,
) => sendJson<T>('POST', path, body, init);

export const patchJson = <T = unknown>(
	path: string,
	body: unknown,
	init?: RequestInit,
) => sendJson<T>('PATCH', path, body, init);

/** GET and parse, with whatever cookies a signed-in spec is carrying. */
export async function getJson<T = unknown>(
	path: string,
	init: RequestInit = {},
): Promise<{ status: number; body: T }> {
	const { request } = await harness();
	const response = await request(path, init);

	return { status: response.status, body: (await response.json()) as T };
}

/**
 * Wait for something the app does *after* answering.
 *
 * A queue worker and a topic subscriber both run on their own clock, so the
 * request that enqueued a job returns before the job is done. Polling to a
 * deadline is the honest way to assert on the result: a fixed sleep is either
 * slower than it needs to be or flaky, and usually both on a loaded machine.
 */
export async function eventually<T>(
	what: () => Promise<T | undefined>,
	{ timeout = 40_000, interval = 250 } = {},
): Promise<T> {
	const deadline = Date.now() + timeout;
	let last: unknown;

	while (Date.now() < deadline) {
		try {
			const result = await what();
			if (result !== undefined && result !== null) return result;
		} catch (error) {
			// Kept, so a timeout reports why it never succeeded rather than only
			// that it did not.
			last = error;
		}

		await new Promise((r) => setTimeout(r, interval));
	}

	throw new Error(
		`Nothing happened within ${timeout}ms${last ? `; last error: ${last}` : ''}`,
	);
}
